### ISSUE TITLE
Download wallet

### ISSUE THREAD

**Issue by perrywoodin** [dashpay/dash-website#43]
http://www-test.dash.org/get-dash/#

Functionality still needs to be developed. Page is currently static.

**Comment by chuckwilliams37** [comment]
I think we've made progress here, but the links need to be reviewed & confirmed. Also the modal popups need design touch (it's presumed that mr.v. is working on this).

**Comment by chuckwilliams37** [comment]
Detection and wallet selection is beleived to be in a release candidate, production-ready state at this time.
