### ISSUE TITLE
JS - Not able to detect best wallet match for iOS

### ISSUE THREAD

**Issue by techieanant** [dashpay/dash-website#430]
**Steps to reproduce**: Visit https://www.dash.org/get-dash/ with an iOS device and see message "We're sorry, but your platform could not be automatically detected. Please select "All Wallets" to find a compatible version."

![wallet detection](https://user-images.githubusercontent.com/7658579/34083816-4d0883b6-e344-11e7-91d1-4b6faa88a000.PNG)

**Description**: The best wallet match for iOS devices is not being detected due to the _vendor_id and _type variables not being set to their correct values on line 54 and 55 in the file /src/js/get-dash.js . 

**Fix**: Set values for _vendor_id and _type as "dash_core" and "mobile" respectively.

![fix](https://user-images.githubusercontent.com/7658579/34083878-625840d4-e345-11e7-89ee-3c8ae02a5e84.PNG)

**Comment by chuckwilliams37** [comment]
Thanks again, @techieanant for your contribution.. and good catch! This is probably an issue that has been present for a long time, unaddressed.  @tungfa - this is another "nice to have" implementation (medium/low priority). I'll bet this was something I personally meant to "come back to " that was forgotten, or de-prioritized.

**Comment by mrleewong** [comment]
@techieanant Good catch! Thanks for collaboration!
Fixed here: https://github.com/dashpay/dash-website/pull/456
