### ISSUE TITLE
Missing images for Payment Processors

### ISSUE THREAD

**Issue by techieanant** [dashpay/dash-website#432]
**Problem**: Images for Payment Processors missing on https://www.dash.org/payments/. The server returns 404 for coinpayments_logo.png, cointopay_logo.png and gourlio_logo.png because the image source points to a non existent wp-content folder presumably used in earlier versions of the website. 

**Solution**: Update image sources to fetch images from /assets/img after adding the payment processor logos to this folder.

**Comment by chuckwilliams37** [comment]
Noted. Thank you!  @tungfa  can we get this one addressed within a reasonable timeframe?

**Comment by mrleewong** [comment]
@techieanant Thanks for your reporting! We fixed this issue.
