### ISSUE TITLE
Dead links on https://www.dash.org/merchants/

### ISSUE THREAD

**Issue by Macr0chip** [dashpay/dash-website#442]
http://www.occuomegawqtkl6j.onion/
http://www.philippengelhorn.com/
http://www.creatable.co.nz/

**Comment by tungfa** [comment]
do NOT touch philippengelhorn.com 
i will be online back soon 🙈
the rest i take care of when on labtop 
tx 

Philipp Engelhorn
Press / Media Relations
www.dash.org

**Comment by nmarley** [comment]
Just verified that these seem to be working:

http://www.philippengelhorn.com/
http://www.creatable.co.nz/

Have tried several Tor circuits and can't connect to http://www.occuomegawqtkl6j.onion/, but this might be expected due to the nature of Tor sites.

**Comment by tungfa** [comment]
http://www.philippengelhorn.com/
http://www.creatable.co.nz/
are both fine (edited)

http://www.occuomegawqtkl6j.onion/
dead
tx
