### ISSUE TITLE
Get Dash - hero buttons

### ISSUE THREAD

**Issue by perrywoodin** [dashpay/dash-website#45]
**User report:** Clicking "setup guide" button and all three buttons to its right takes you to "learn how to set up your wallet" section further down, requiring another click. Maybe just send the user to the intended destination?

I would like to defer this issue until we get some additional feedback. If we link directly to the Wiki, the page will function differently from other pages.

**Comment by chuckwilliams37** [comment]
Marking resolved. All mentioned buttons navigate to intra-page links. There off-site detailed links are available for each subject.
