### ISSUE TITLE
404 Error - /Network Page

### ISSUE THREAD

**Issue by Thoughtscript** [dashpay/dash-website#450]
Hi! I'm new here so please let me know if I'm doing something wrong!

I'm seeing several 404 errors on my local machine: http://localhost:3000/network/ such that some of the data isn't populating. Not sure if that's a setup issue or relevant problem. I'll dig around a bit more. At the very least, we should be able to do some caching here if it's just a local issue (if we aren't already).

I can also update any documentation to smooth the setup process out for others too!

![image](https://dl.dropboxusercontent.com/s/po8ucknzdvtlevl/Capture.PNG?dl=0 "404")

**Comment by mrleewong** [comment]
Hi, @Thoughtscript 
Actually it's not an issue, you just need to run web-site api on your own machine.
Here is a repo:
https://github.com/dashpay/dash-website-api

**Comment by Thoughtscript** [comment]
Ah thank you! Just saw this :)
