### ISSUE TITLE
UI/UX Intuitively want to click on card [good first issue]

### ISSUE THREAD

**Issue by beornborn** [dashpay/dash-website#547]
on https://www.dash.org/evolution/

Cards are not clickable. May be confusing for some users.

![da222](https://user-images.githubusercontent.com/1485786/39005178-231599a2-4408-11e8-88eb-451336845e30.png)

possible solutions:
- make cards redirect to correspondent article on click

If you think this is a reasonable thing to do, let me know and I'll send a PR

**Comment by chuckwilliams37** [comment]
@tungfa @mrleewong - can we have someone take a look at this one?

**Comment by mrleewong** [comment]
@beornborn Good catch! Thank you. 
Fixed in #553
